services:
  nginx:
    depends_on:
      - flask_blog
      - certbot
    image: nginx:stable
    restart: always
    links:
        - flask_blog
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes :
      - ./certbot/www:/var/www/certbot/:rw 
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    image: postgres:12-bullseye
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 3s
      retries: 10

  flask_blog:
    image: sahilsagwekar2652/personal-blog-website:master
    depends_on:
      db:
        condition: service_started
    env_file:
      - .env
    environment:
      DATABASE_URL: db 
    links:
      - db
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

volumes:
  postgres_data:
    name: "db_volume"
