services:
  nginx:
    depends_on:
      flask_blog:
        condition: service_healthy
    build:
      nginx
    links:
        - flask_blog
    ports:
      - 80:80

  db:
    image: postgres:12-bullseye
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 3s
      retries: 10

  flask_blog:
    depends_on:
      db:
        condition: service_healthy
    build:
      flask_blog
    env_file:
      - .env
    environment:
      DATABASE_URL: db 
    links:
      - db
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    # ports:
    #   - "0.0.0.0:80:5000"
