name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  docker:
    if: ${{ contains(github.event.head_commit.message, 'Build Image') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push flask_blog
        uses: docker/build-push-action@v5
        with:
          context: https://github.com/sahil-sagwekar2652/Personal-blog-website.git#master:flask_blog
          push: true
          tags: sahilsagwekar2652/personal-blog-website:${{ env.RELEASE_VERSION }}
